/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as DashboardIndexRouteImport } from './routes/dashboard/index'
import { Route as DashboardProductsRouteImport } from './routes/dashboard/products'
import { Route as AuthRegisterRouteImport } from './routes/auth/register'
import { Route as AuthLoginRouteImport } from './routes/auth/login'
import { Route as DashboardProductsIndexRouteImport } from './routes/dashboard/products/index'
import { Route as DashboardProductsIdRouteImport } from './routes/dashboard/products/$id'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardIndexRoute = DashboardIndexRouteImport.update({
  id: '/dashboard/',
  path: '/dashboard/',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardProductsRoute = DashboardProductsRouteImport.update({
  id: '/dashboard/products',
  path: '/dashboard/products',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRegisterRoute = AuthRegisterRouteImport.update({
  id: '/auth/register',
  path: '/auth/register',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthLoginRoute = AuthLoginRouteImport.update({
  id: '/auth/login',
  path: '/auth/login',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardProductsIndexRoute = DashboardProductsIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => DashboardProductsRoute,
} as any)
const DashboardProductsIdRoute = DashboardProductsIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => DashboardProductsRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/auth/login': typeof AuthLoginRoute
  '/auth/register': typeof AuthRegisterRoute
  '/dashboard/products': typeof DashboardProductsRouteWithChildren
  '/dashboard': typeof DashboardIndexRoute
  '/dashboard/products/$id': typeof DashboardProductsIdRoute
  '/dashboard/products/': typeof DashboardProductsIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth/login': typeof AuthLoginRoute
  '/auth/register': typeof AuthRegisterRoute
  '/dashboard': typeof DashboardIndexRoute
  '/dashboard/products/$id': typeof DashboardProductsIdRoute
  '/dashboard/products': typeof DashboardProductsIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/auth/login': typeof AuthLoginRoute
  '/auth/register': typeof AuthRegisterRoute
  '/dashboard/products': typeof DashboardProductsRouteWithChildren
  '/dashboard/': typeof DashboardIndexRoute
  '/dashboard/products/$id': typeof DashboardProductsIdRoute
  '/dashboard/products/': typeof DashboardProductsIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/auth/login'
    | '/auth/register'
    | '/dashboard/products'
    | '/dashboard'
    | '/dashboard/products/$id'
    | '/dashboard/products/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/auth/login'
    | '/auth/register'
    | '/dashboard'
    | '/dashboard/products/$id'
    | '/dashboard/products'
  id:
    | '__root__'
    | '/'
    | '/auth/login'
    | '/auth/register'
    | '/dashboard/products'
    | '/dashboard/'
    | '/dashboard/products/$id'
    | '/dashboard/products/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthLoginRoute: typeof AuthLoginRoute
  AuthRegisterRoute: typeof AuthRegisterRoute
  DashboardProductsRoute: typeof DashboardProductsRouteWithChildren
  DashboardIndexRoute: typeof DashboardIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard/': {
      id: '/dashboard/'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof DashboardIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard/products': {
      id: '/dashboard/products'
      path: '/dashboard/products'
      fullPath: '/dashboard/products'
      preLoaderRoute: typeof DashboardProductsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth/register': {
      id: '/auth/register'
      path: '/auth/register'
      fullPath: '/auth/register'
      preLoaderRoute: typeof AuthRegisterRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth/login': {
      id: '/auth/login'
      path: '/auth/login'
      fullPath: '/auth/login'
      preLoaderRoute: typeof AuthLoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard/products/': {
      id: '/dashboard/products/'
      path: '/'
      fullPath: '/dashboard/products/'
      preLoaderRoute: typeof DashboardProductsIndexRouteImport
      parentRoute: typeof DashboardProductsRoute
    }
    '/dashboard/products/$id': {
      id: '/dashboard/products/$id'
      path: '/$id'
      fullPath: '/dashboard/products/$id'
      preLoaderRoute: typeof DashboardProductsIdRouteImport
      parentRoute: typeof DashboardProductsRoute
    }
  }
}

interface DashboardProductsRouteChildren {
  DashboardProductsIdRoute: typeof DashboardProductsIdRoute
  DashboardProductsIndexRoute: typeof DashboardProductsIndexRoute
}

const DashboardProductsRouteChildren: DashboardProductsRouteChildren = {
  DashboardProductsIdRoute: DashboardProductsIdRoute,
  DashboardProductsIndexRoute: DashboardProductsIndexRoute,
}

const DashboardProductsRouteWithChildren =
  DashboardProductsRoute._addFileChildren(DashboardProductsRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthLoginRoute: AuthLoginRoute,
  AuthRegisterRoute: AuthRegisterRoute,
  DashboardProductsRoute: DashboardProductsRouteWithChildren,
  DashboardIndexRoute: DashboardIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
